// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type SavedBillPayment struct {
	ID           int32          `json:"id"`
	MerchantID   int32          `json:"merchant_id"`
	CustomerID   int32          `json:"customer_id"`
	SubsciberNo  int32          `json:"subsciber_no"`
	Description  sql.NullString `json:"description"`
	Isshowib     sql.NullString `json:"isshowib"`
	Isshowmobile sql.NullString `json:"isshowmobile"`
	Amount       sql.NullString `json:"amount"`
	Isfavorite   sql.NullString `json:"isfavorite"`
}
