// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateSavedBillPayment(ctx context.Context, arg CreateSavedBillPaymentParams) (sql.Result, error)
	DeleteSavedBillPayment(ctx context.Context, id int64) error
	GetSavedBillPayment(ctx context.Context, id int64) (SavedBillPayment, error)
	ListSavedBillPayment(ctx context.Context, arg ListSavedBillPaymentParams) ([]SavedBillPayment, error)
	UpdateSavedBillPayment(ctx context.Context, arg UpdateSavedBillPaymentParams) error
}

var _ Querier = (*Queries)(nil)
