// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SavedBillPaymentServiceClient is the client API for SavedBillPaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SavedBillPaymentServiceClient interface {
	CreateSavedBillPayment(ctx context.Context, in *CreateSavedBillPaymentRequest, opts ...grpc.CallOption) (*CreateSavedBillPaymentResponse, error)
}

type savedBillPaymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSavedBillPaymentServiceClient(cc grpc.ClientConnInterface) SavedBillPaymentServiceClient {
	return &savedBillPaymentServiceClient{cc}
}

func (c *savedBillPaymentServiceClient) CreateSavedBillPayment(ctx context.Context, in *CreateSavedBillPaymentRequest, opts ...grpc.CallOption) (*CreateSavedBillPaymentResponse, error) {
	out := new(CreateSavedBillPaymentResponse)
	err := c.cc.Invoke(ctx, "/proto.SavedBillPaymentService/CreateSavedBillPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SavedBillPaymentServiceServer is the server API for SavedBillPaymentService service.
// All implementations must embed UnimplementedSavedBillPaymentServiceServer
// for forward compatibility
type SavedBillPaymentServiceServer interface {
	CreateSavedBillPayment(context.Context, *CreateSavedBillPaymentRequest) (*CreateSavedBillPaymentResponse, error)
	mustEmbedUnimplementedSavedBillPaymentServiceServer()
}

// UnimplementedSavedBillPaymentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSavedBillPaymentServiceServer struct {
}

func (UnimplementedSavedBillPaymentServiceServer) CreateSavedBillPayment(context.Context, *CreateSavedBillPaymentRequest) (*CreateSavedBillPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSavedBillPayment not implemented")
}
func (UnimplementedSavedBillPaymentServiceServer) mustEmbedUnimplementedSavedBillPaymentServiceServer() {
}

// UnsafeSavedBillPaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SavedBillPaymentServiceServer will
// result in compilation errors.
type UnsafeSavedBillPaymentServiceServer interface {
	mustEmbedUnimplementedSavedBillPaymentServiceServer()
}

func RegisterSavedBillPaymentServiceServer(s grpc.ServiceRegistrar, srv SavedBillPaymentServiceServer) {
	s.RegisterService(&SavedBillPaymentService_ServiceDesc, srv)
}

func _SavedBillPaymentService_CreateSavedBillPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSavedBillPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavedBillPaymentServiceServer).CreateSavedBillPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SavedBillPaymentService/CreateSavedBillPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavedBillPaymentServiceServer).CreateSavedBillPayment(ctx, req.(*CreateSavedBillPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SavedBillPaymentService_ServiceDesc is the grpc.ServiceDesc for SavedBillPaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SavedBillPaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SavedBillPaymentService",
	HandlerType: (*SavedBillPaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSavedBillPayment",
			Handler:    _SavedBillPaymentService_CreateSavedBillPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "savedbillpayment_service.proto",
}
